// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ExplicitlyStated.StateMachineFactory.ThrowCustomConfigurationImplementationError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ExplicitlyStated.StateMachineFactory.CreateSimple``2(``0,ExplicitlyStated.Configuration.IStateMachineConfiguration{``0,``1})~ExplicitlyStated.StateMachine.ISimpleStateMachine{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ExplicitlyStated.StateMachineFactory.CreateAsync``2(``0,ExplicitlyStated.Configuration.IAsyncStateMachineConfiguration{``0,``1})~ExplicitlyStated.StateMachine.IStateMachine{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ExplicitlyStated.StateMachineFactory.CreateEvent``3(``0,ExplicitlyStated.Configuration.IAsyncStateMachineConfiguration{``0,``1})~ExplicitlyStated.EventStateMachine.IEventStateMachine{``0,``1,``2}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ExplicitlyStated.StateMachineFactory.CreateEvent``3(``0,ExplicitlyStated.EventStateMachine.Configuration.IStateMachineConfiguration{``0,``1,``2})~ExplicitlyStated.EventStateMachine.IEventStateMachine{``0,``1,``2}")]
